[workspace]
members = [
        "lampo-common",
        "lampod",
        "lampod-cli",
        "lampo-cli",
        "lampo-bitcoind",
        "lampo-httpd",
        "lampo-core-wallet",
        "lampo-testing",
        "tests/tests", 
        "lampo-ldk-node",
]

default-members = [
        "lampo-common",
        "lampod",
        "lampod-cli",
        "lampo-cli",
        "lampo-bitcoind",
        "lampo-httpd",
        "lampo-core-wallet",
        "lampo-ldk-node",
]
resolver = "2"