[package]
name = "lampod"
version = "0.0.1"
edition = "2021"

[dependencies]
lampo-common = { path = "../lampo-common", default-features = false, optional = true }
lampo-jsonrpc = { path = "../lampo-jsonrpc", optional = true }
lampo-client = { path = "../lampo-client", default-features = false, optional = true }

tokio = { version = "^1.29.1", features = ["rt-multi-thread", "parking_lot"] }
log = "0.4.17"
time = "0.3.13"
futures = "0.3.28"
crossbeam-channel = "0.5.8"
once_cell = "1.17.1"
async-trait = "0.1.68"

[features]
default = []
vanilla = ["lampo-common/vanilla", "lampo-client/vanilla", "lampo-jsonrpc"]
rgb = ["lampo-common/rgb", "lampo-jsonrpc"]
