[package]
name = "lampod"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.38.0", features = ["time"] }
async-trait = "0.1.80"
serde = "1"
lampo-common = { path = "../lampo-common" }
lampo-async-jsonrpc = { path = "../lampo-async-jsonrpc" }
lampo-client = { path = "../lampo-client" }
log = "0.4.17"
time = "0.3.13"
futures = "0.3.28"
